server.port=8083

spring.datasource.url=jdbc:mysql://localhost:3306/fintrack_analytics?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=analytics-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.fintrack.transactionservice.event

app.jwt.secret=fintrack-super-secret-key-must-be-at-least-256-bits-long-yes
app.jwt.expiration=86400000