spring.application.name=user-service
server.port=8081

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/fintrack_users?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=${APP_JWT_SECRET:fintrack-super-secret-key-must-be-at-least-256-bits-long-yes}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}